name: cron-create-daily-trivia
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: post /api/daily-trivia
        run: curl -X POST https://geobuff-dev.ts.r.appspot.com/api/daily-trivia
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/927094486260154418/BjAaAvQDK3GFAoTFBKF04Kq-GHAjeuPbZJ1V-aXwQPFDL2glaUtCsmY8VrcWaX_XOUCY
          DISCORD_AVATAR: https://i.guim.co.uk/img/media/470513f37bcacf045d006841311af6bfb24c9422/0_335_5019_3011/master/5019.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=417df3459afaf38cb5f775e17f0e3359
        uses: Ilshidur/action-discord@master  
        with:
            args: 'Daily trivia for ${{ steps.date.outputs.date }} has been successfully published'

