name: cron-create-daily-trivia
on:
  schedule:
    - cron: '0 11 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: create dev trivia questions
        run: curl -X POST https://geobuff-dev.ts.r.appspot.com/api/daily-trivia
      - name: create prod trivia questions
        run: curl -X POST https://geobuff-prod-317101.ts.r.appspot.com/api/daily-trivia
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/927094486260154418/BjAaAvQDK3GFAoTFBKF04Kq-GHAjeuPbZJ1V-aXwQPFDL2glaUtCsmY8VrcWaX_XOUCY
          DISCORD_AVATAR: https://botmywork.com/wp-content/uploads/2018/09/facebook-messenger-bot-feature-images.jpg
        uses: Ilshidur/action-discord@master  
        with:
            args: 'Daily trivia for ${{ steps.date.outputs.date }} has been successfully published.'

