name: dev-cron-create-daily-trivia
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: post /api/daily-trivia
        run: curl -X POST https://geobuff-dev.ts.r.appspot.com/api/daily-trivia
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/927094486260154418/BjAaAvQDK3GFAoTFBKF04Kq-GHAjeuPbZJ1V-aXwQPFDL2glaUtCsmY8VrcWaX_XOUCY
        uses: Ilshidur/action-discord@master  
        with:
            args: 'Daily trivia has been published'

